'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.34209
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace My
    
    <Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "11.0.0.0"),  _
     Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Partial Friend NotInheritable Class MySettings
        Inherits Global.System.Configuration.ApplicationSettingsBase
        
        Private Shared defaultInstance As MySettings = CType(Global.System.Configuration.ApplicationSettingsBase.Synchronized(New MySettings()),MySettings)
        
#Region "My.Settings Auto-Save Functionality"
#If _MyType = "WindowsForms" Then
    Private Shared addedHandler As Boolean

    Private Shared addedHandlerLockObject As New Object

    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
    Private Shared Sub AutoSaveSettings(ByVal sender As Global.System.Object, ByVal e As Global.System.EventArgs)
        If My.Application.SaveMySettingsOnExit Then
            My.Settings.Save()
        End If
    End Sub
#End If
#End Region
        
        Public Shared ReadOnly Property [Default]() As MySettings
            Get
                
#If _MyType = "WindowsForms" Then
               If Not addedHandler Then
                    SyncLock addedHandlerLockObject
                        If Not addedHandler Then
                            AddHandler My.Application.Shutdown, AddressOf AutoSaveSettings
                            addedHandler = True
                        End If
                    End SyncLock
                End If
#End If
                Return defaultInstance
            End Get
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property DNACharsOnly() As Boolean
            Get
                Return CType(Me("DNACharsOnly"),Boolean)
            End Get
            Set
                Me("DNACharsOnly") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property AllowNegativeScores() As Boolean
            Get
                Return CType(Me("AllowNegativeScores"),Boolean)
            End Get
            Set
                Me("AllowNegativeScores") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Green")>  _
        Public Property GraphicResultsMatchColor() As Global.System.Drawing.Color
            Get
                Return CType(Me("GraphicResultsMatchColor"),Global.System.Drawing.Color)
            End Get
            Set
                Me("GraphicResultsMatchColor") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Blue")>  _
        Public Property GraphicResultsSeq1GapColor() As Global.System.Drawing.Color
            Get
                Return CType(Me("GraphicResultsSeq1GapColor"),Global.System.Drawing.Color)
            End Get
            Set
                Me("GraphicResultsSeq1GapColor") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Red")>  _
        Public Property GraphicResultsSeq2GapColor() As Global.System.Drawing.Color
            Get
                Return CType(Me("GraphicResultsSeq2GapColor"),Global.System.Drawing.Color)
            End Get
            Set
                Me("GraphicResultsSeq2GapColor") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Yellow")>  _
        Public Property GraphicResultsCurrentColor() As Global.System.Drawing.Color
            Get
                Return CType(Me("GraphicResultsCurrentColor"),Global.System.Drawing.Color)
            End Get
            Set
                Me("GraphicResultsCurrentColor") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property DisplaySequence1Numbers() As Boolean
            Get
                Return CType(Me("DisplaySequence1Numbers"),Boolean)
            End Get
            Set
                Me("DisplaySequence1Numbers") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property DisplaySequence2Numbers() As Boolean
            Get
                Return CType(Me("DisplaySequence2Numbers"),Boolean)
            End Get
            Set
                Me("DisplaySequence2Numbers") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("10")>  _
        Public Property DisplayNumbersEvery() As Integer
            Get
                Return CType(Me("DisplayNumbersEvery"),Integer)
            End Get
            Set
                Me("DisplayNumbersEvery") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property DimMismatches() As Boolean
            Get
                Return CType(Me("DimMismatches"),Boolean)
            End Get
            Set
                Me("DimMismatches") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property ViewFullTracebackGraph() As Boolean
            Get
                Return CType(Me("ViewFullTracebackGraph"),Boolean)
            End Get
            Set
                Me("ViewFullTracebackGraph") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("White")>  _
        Public Property GraphicResultsSelectionColor() As Global.System.Drawing.Color
            Get
                Return CType(Me("GraphicResultsSelectionColor"),Global.System.Drawing.Color)
            End Get
            Set
                Me("GraphicResultsSelectionColor") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property ShowGridLinesPartialPath() As Boolean
            Get
                Return CType(Me("ShowGridLinesPartialPath"),Boolean)
            End Get
            Set
                Me("ShowGridLinesPartialPath") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property SequenceDensityColors() As Boolean
            Get
                Return CType(Me("SequenceDensityColors"),Boolean)
            End Get
            Set
                Me("SequenceDensityColors") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property DotPlotInColor() As Boolean
            Get
                Return CType(Me("DotPlotInColor"),Boolean)
            End Get
            Set
                Me("DotPlotInColor") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property ShowGridLinesDotPlot() As Boolean
            Get
                Return CType(Me("ShowGridLinesDotPlot"),Boolean)
            End Get
            Set
                Me("ShowGridLinesDotPlot") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property ShowGridLinesDensityColor() As Boolean
            Get
                Return CType(Me("ShowGridLinesDensityColor"),Boolean)
            End Get
            Set
                Me("ShowGridLinesDensityColor") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property UseWindowingForDotPlot() As Boolean
            Get
                Return CType(Me("UseWindowingForDotPlot"),Boolean)
            End Get
            Set
                Me("UseWindowingForDotPlot") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property SimpleSequenceLineView() As Boolean
            Get
                Return CType(Me("SimpleSequenceLineView"),Boolean)
            End Get
            Set
                Me("SimpleSequenceLineView") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("3")>  _
        Public Property numberOfAlignmentsToCompare() As Integer
            Get
                Return CType(Me("numberOfAlignmentsToCompare"),Integer)
            End Get
            Set
                Me("numberOfAlignmentsToCompare") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property compareIn3D() As Boolean
            Get
                Return CType(Me("compareIn3D"),Boolean)
            End Get
            Set
                Me("compareIn3D") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("10")>  _
        Public Property markerSizeCompare() As Integer
            Get
                Return CType(Me("markerSizeCompare"),Integer)
            End Get
            Set
                Me("markerSizeCompare") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property compareInSeparateCharts() As Boolean
            Get
                Return CType(Me("compareInSeparateCharts"),Boolean)
            End Get
            Set
                Me("compareInSeparateCharts") = value
            End Set
        End Property
    End Class
End Namespace

Namespace My
    
    <Global.Microsoft.VisualBasic.HideModuleNameAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Module MySettingsProperty
        
        <Global.System.ComponentModel.Design.HelpKeywordAttribute("My.Settings")>  _
        Friend ReadOnly Property Settings() As Global.LocalAlignmentVisualization.My.MySettings
            Get
                Return Global.LocalAlignmentVisualization.My.MySettings.Default
            End Get
        End Property
    End Module
End Namespace
